### ISSUE TITLE
关于第二次作业题目描述的疑问

### ISSUE THREAD

**Issue by j31234** [thu-coai/THUOOP#13]
第二次作业C题第1小题B项

> B) 在代码int f(auto x) { … }中，由于编译器不能在编译器确定x的数据类型，因此不能通过编译

这里是按照c++20之前还是c++20标准？这段代码在c++20中可以编译通过。

> [简写函数模板](https://zh.cppreference.com/w/cpp/language/function_template)
> 当函数声明或函数模板声明的形参列表中出现占位符类型（auto 或 Concept auto）时，该声明声明一个函数模板，并且为每个占位符向模板形参列表追加一个虚设的模板形参(C++20 起)

（实测g++在c++14以上时已经支持用auto简写函数模板）

**Comment by hzhwcmhf** [comment]
已修正
