### ISSUE TITLE
关于第5次作业选择题第7题选项的疑问

### ISSUE THREAD

**Issue by weiz0823** [thu-coai/THUOOP#19]
> 7 关于以下代码，说法正确的是
> C mysort1和mysort2的区别在于，comp在mysort1中是早绑定，在mysort2中是晚绑定。

这里面的comp是泛指所有模板实例中的参数还是特指某个模板实例中的参数？

**Comment by hzhwcmhf** [comment]
我觉得这个不存在问题，在编译期确定调用的函数就是早绑定，运行期确定就是晚绑定

**Comment by weiz0823** [comment]
可是在Compare = CompCls, comp = CompCls()和Compare = function<bool(int, int)>, comp = fn的时候mysort1由于模板参数的不同会表现出不同行为，这个选项是要对于所有的模板参数正确才算正确吗？

**Comment by hzhwcmhf** [comment]
我明白你的意思了，现在选项做了修改
