### ISSUE TITLE
用校内Git做答疑？

### ISSUE THREAD

**Issue by Steaunk** [thu-coai/THUOOP#7]
GitHub访问不稳定，是否可以考虑用git.tsinghua.edu.cn来做答疑。

**Comment by hzhwcmhf** [comment]
我们尝试了一下，校内git需要校外无法访问。目前我们没找到更好的选项，如果有别的建议可以提

**Comment by Steaunk** [comment]
校外可以访问，访问方法同info.tsinghua.edu.cn，可以通过https://webvpn.tsinghua.edu.cn/login 来访问。@hzhwcmhf

**Comment by hzhwcmhf** [comment]
你要是挂了学校vpn一样可以上github

**Comment by Steaunk** [comment]
挂了学校VPN上github和没挂有啥区别？行的吧。
